management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator
      path-mapping:
        prometheus: /metrics
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
